### ISSUE TITLE
http_status plugin should work with both "links" and "elinks"

### ISSUE THREAD

**Issue by petecassetta** [rackerlabs/recap#235] opened 2020-11-10 15:59 UTC
The Apache status report has always been OK with either links or elinks. But if someone configures it with links, all they get in the recap log is:

elinks is not installed

This is easy to fix. Just edit line 40:
Current: http_tool=$( type -p elinks )
Fixed: http_tool=$( type -p elinks || type -p links )

**Comment by tonyskapunk** [comment] 2020-11-10 16:47
Hi, @petecassetta thanks for opening this issue.

We used to support `links` but the problem is that it will pull so many packages that [we decided to drop it and use `elinks` (#170)](https://github.com/rackerlabs/recap/issues/170).

Granted, we don't force people to have `elinks` installed rather we [recommend it](https://src.fedoraproject.org/rpms/recap/blob/master/f/recap.spec#_29)  as [discussed in this issue](https://github.com/rackerlabs/recap/issues/169#issuecomment-433666152). We went on this path because we wanted to reduce the number of dependencies.

I'd suggest in this case to install `elinks`, that would be the quickest way to get that solved. Let me know if there's a limitation with the installation of `elinks`.

Thanks again!

**Comment by petecassetta** [comment] 2020-11-10 17:16
Yes, of course elinks is more lightweight. But if people are happily using the Apache status report with links, and they configure the http_status plugin, it is surprising that it fails to give them any information. My recommended code does not require links in any way, in fact it prefers elinks. But it allows recap to log meaningful results on a server that is already configured with links instead of elinks. I don't see the downside of that.

It doesn't seem that the recap package in EPEL pulls in elinks or links. Is that an oversight? Perhaps you intended to have elinks as a dependency? The only dependency I saw get installed was iotop.

**Comment by petecassetta** [comment] 2020-11-10 17:26
Alternatively, if recap is going to only support elinks, I think that should be documented somewhere, maybe in the header of the http_status script, the project wiki, etc. so that users don't need to read the code to discover that behavior. Is there a document somewhere that specifies which binaries recap requires? I remember you telling me once that you switched from netstat to ss, for example.

**Comment by petecassetta** [comment] 2020-11-10 17:43
Maybe a good solution would be to add elinks to the dependencies, as I see it is not there:

# CentOS 6
$ rpm -qR recap
/bin/bash  
/bin/sh  
config(recap) = 2.1.0-6.el6
crontabs  
iotop  
iproute  
procps  
psmisc  
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(VersionedDependencies) <= 3.0.3-1
sysstat >= 9
rpmlib(PayloadIsXz) <= 5.2-1

# CentOS 7
$ rpm -qR recap
/bin/bash
/bin/sh
config(recap) = 2.1.0-6.el7
crontabs
iotop
iproute
procps-ng
psmisc
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
sysstat >= 9
rpmlib(PayloadIsXz) <= 5.2-1

**Comment by tonyskapunk** [comment] 2020-11-10 20:10
>  I think that should be documented somewhere,

It is documented in the [README under dependencies](https://github.com/rackerlabs/recap#dependencies).  But I agree is not clear, that should be documented in a better way.

> the project wiki,

:disappointed: That needs a major update. I know @stephenlang had a great improvement for the wiki but not sure if he is still able to help with it.

> It doesn't seem that the recap package in EPEL pulls in elinks or links. Is that an oversight?

Sorry for the confusion, I meant that we don't have `elinks` as a dependency at all. The only difference is that EPEL packages above 7 and fedora have `elinks` as a recommendation:

```
[root@9fb77a7f5c91 /]# echo $(. /etc/os-release; echo ${PRETTY_NAME})
CentOS Linux 8 (Core)

[root@9fb77a7f5c91 /]# rpm --recommends -q recap
elinks
```

I know this feels odd, but if you compare `http` to `mysql` reports, now they both are aligned by *not* pulling extra dependencies. We have never added mysql client as a dependency despite having a report for it.

Digging a bit further about `links` support I found this:
- `el6` is EOL by the [end of the month](https://endoflife.software/operating-systems/linux/centos)
- `el7` EOL is [Jun 2024](https://endoflife.software/operating-systems/linux/centos)
- In `el8` [`links` is gone and is replaced by `elinks`](https://centos.pkgs.org/8/centos-powertools-x86_64/):
  
  ```bash
  [root@d1e52a7a6d6e /]# rpm -q --provides elinks
  config(elinks) = 0.12-0.58.pre6.el8
  elinks = 0.12-0.58.pre6.el8
  elinks(x86-64) = 0.12-0.58.pre6.el8
  links = 1:0.97-1         <-----
  text-www-browser
  webclient
  ```

I'm wondering how valuable would be to add `links` that only exist in `el7`. :thinking:

**Comment by petecassetta** [comment] 2020-11-10 21:24
This item is not an urgent priority at all, it still just seems like an odd design decision to force use of elinks when links is equally acceptable to apachectl and people have been happily using both utilities to view the Apache status report for years. I've already updated our internal wiki's to communicate that elinks should be used, and this item probably isn't worth as much discussion as we've already given it :-), so if you prefer to just close this and leave things as-is, that's fine.

**Comment by tonyskapunk** [comment] 2020-11-11 15:05
I hear you, sorry it feels this strange.

Nonetheless, despite the abruptness, I believe it was a good move as we reduced lots of dependencies. Additionally, we are having a double benefit as `links` is replaced by `elinks`.

I'll go ahead and close this now, thanks again for taking the time to open this issue.

**Closed as completed by tonyskapunk** 2020-11-11 15:05 UTC
Labels: question, wontfix
