### ISSUE TITLE
create branches for dev and stable releases

### ISSUE THREAD

**Issue by buzzboy23** [rackerlabs/recap#20] opened 2014-09-19 01:05 UTC
Request from the Rackspace RPM-dev team is to create branches with tags for dev and stable releases.  RPM builds at Rackspace (and any other builds for other packagers) would be pulled from stable releases where a tar would be created.

**Comment by bhgraham** [comment] 2015-01-31 15:58
Branches for master and development and tags for 0.9.8, stable, and development created.
Closing this.

**Comment by cgtx** [comment] 2015-02-05 15:44
Having a tag `development` is causing issues for me when I try to check out the `development` branch.  It results in a detached HEAD state.  Tags should only be used for releases.  I don't see the point in having a tag named `development` since that will be constantly changing.  Likewise, a tag for `stable` doesn't make much sense, stable should be the latest version tag.

If no one is opposed, I'm going to delete the `dev`,`development`, and `stable` tags (but of course leave the branches).

**Comment by bhgraham** [comment] 2015-02-05 17:19
I had made the tag name "dev" to prevent this, but I didn't see a point in a tagged dev either.  Anyone else think we need this?

**Comment by thebwt** [comment] 2016-06-07 17:51
While the letter of the issue is complete, the spirit is thus:

##Master is stablish
That means that at any given point master is broken while someone is trying to work an issue with commits directly to master, it should be working but will ceratinly have ..

##**Issues** are resolved in their own branch
When we have a hypothetical solution to an issue, you open a pull request against a new branch for that issue "issue/15" as an example branch name.

##Releases are vetted and super-stable
Not ever fix needs a new release, release at new feature milestones or some time-determined bugfix release schedule (e.g. every 2 weeks).

We currently have a master branch that is stable, and we have various pull requests for solutions to issues, so I don't think this is a problem anymore. If we have people doing direct commits to master still, we can restrict who has push access just to master.

Closing this.

**Comment by tonyskapunk** [comment] 2017-01-13 15:30
I'm seeing the same issues as @cgtx (when moving to `development` branch I get into a `detached HEAD` state, I've compared the commits in that branch and in `master` and there is no difference up to 66cc7f1 where `development` `HEAD` is, I have no preference either using [`Git-Flow`][1] or [`GitHub Flow`][2] but as @thebwt has pointed out all the PRs in the last year have been following the latter, then I'm removing `development`, besides package wise, we are only packaging what's tagged as a release.

[1]: https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow
[2]: https://guides.github.com/introduction/flow/

**Closed by tonyskapunk** 2017-01-13 15:30 UTC
Labels: enhancement
