### ISSUE TITLE
change processor utilisation report; report inaccurate

### ISSUE THREAD

**Issue by kimvette** [rackerlabs/recap#39] opened 2015-12-10 23:24 UTC
Hi team! 

I'd like to point out that relying on 'ps' for processor utilisation can lead to incorrect conclusions and if used for alert generation, can raise tickets based on outdated data. Why? From the ps man page: 

> CPU usage is currently expressed as the percentage of time 
> spent running during the entire lifetime of a process.  
> This is not ideal, and it does not conform to the standards
> that ps otherwise conforms to.  CPU usage is unlikely to add 
> up to exactly 100%.

Looking at processsor utilisation via "ps" isn't worthless; it is useful for identifying long-term trends but consider this: you've had a server that has been up for a few months and had a very heavy load but it is a single server behind a load balancer, and now your budget allows you to add three more nodes (and actually make use of the load balancer!) so you add the servers and pool members but have not restarted the java process on the original node. You want to make sure that the load is evenly spread so you install recap for monitoring and have your ticketing system parse the logs to generate alerts where appropriate. Your ticketing system is now generating alerts for the original node because the CPU utilisation reported by PS is based on many months' worth of of 90%+ CPU utilisation and the average will take weeks to drop to your "warning" threshold. 

A better method would be to run something like "top -d 5 -n 2" (naturally additional switches will be required for full output), discarding the first report and capturing the second; this would give a more relevant metric to raise alerts on and eliminate false alerts resulting from a historical average that has been addressed but not yet reflected by ps -- or maybe there is another method which would be less cumbersome. 

But, the bottom line is relying on ps can result in false conclusions if you're trying to diagnose an issue, have applied some changes and are trying to figure out why it is still reporting high utilisation (when using ps) and generating alerts.

**Comment by man-chung** [comment] 2015-12-11 12:38
Hi,

Thank you for your feedback,

The design intention was not to alert for CPU utilisation - there are far more accurate, reliable, and timely tools/methods that fullfil that role (in real time, rather than waiting to parsing the recap output files).

Recap was designed to allow administrators a point in time view of the state of the server (likely, during the time of an incident/issue), much like if the admin was there to run the commands at the time. So as you mentioned, trend is more desirable from this point of view.

**Comment by Beerey** [comment] 2016-01-27 09:21
Realistically recap gets mostly used for investigation of performance issues.  I think having a "top 10 CPU using processes" list in there is misleading at best.  99/100 sysadmins would read that section as giving information similar to top (what are the processes using the most CPU within a second or two of when recap runs?) when in actual fact it's giving nothing of the sort.  For processes which are long lived - for example MySQL or other DBs - there is not necessarily any useful information provided by the top 10 CPU section of resources.log, and for others like Apache there may not be useful information depending on the circumstances (if the site is low traffic, has a high MaxRequestsPerChild, etc).

I'd +1 Kimberly's feedback.  I would personally find it really useful to see CPU usage over a few seconds, and at the least I think the title should be clarified so techs aren't reading the recap logs and thinking it's the highest CPU users at that point in time, instead of over the process lifetime.  I can see value in being able to see both the top CPU consumers provided by ps and by something like top, but I'd note that we already capture a full process list in ps.log so maybe (if someone really needs that information) they could look there - it's not hard to write a oneliner to sort the output.

**Comment by piersc** [comment] 2016-01-27 09:46
+1 for this change - recap should represent a snapshot of a point in time, not an average over an unclear period.

**Comment by kimvette** [comment] 2016-02-06 20:32
Any update on this? 

On the flip side of the coin - if a long-running process is suddenly overwhelming the system it may not even be reported in the top ten CPU consuming processes in the recap snapshots, because the average that ps reports will not be noticeably higher unless the high utilisation is over a comparatively long period of time so the wrong processes will be captured by recap.

**Comment by eljrax** [comment] 2016-02-08 11:07
@Beerey @piersc 

Just spoken with @man-chung - and we're OK with this change as well. Do either of you want to submit a PR with this enhancement?

**Comment by piersc** [comment] 2016-02-08 16:03
Like Kim says, although we can get this with something like top -d 5 -n 2 its pretty ugly; is there some better option you know of that we could use @eljrax ?

**Comment by eljrax** [comment] 2016-02-10 14:16
@piersc  - There's always `pidstat` - part of the sysstat package.

```
# pidstat 2 2 | egrep "^Average:"
Average:          PID    %usr %system  %guest    %CPU   CPU  Command
Average:        24829   94.53    0.00    0.00   94.53     -  stress
Average:        24830   93.53    0.00    0.00   93.53     -  stress
Average:        24844    0.00    0.50    0.00    0.50     -  pidstat
```

It can also do memory (with -r)

**Comment by carlwgeorge** [comment] 2016-05-26 17:58
If we are going to use pidstat, that is going to imply a minimum version of sysstat.  I don't know what version it was added in, but it doesn't exist in EL5's sysstat 7.0.2.

**Comment by carlwgeorge** [comment] 2016-05-26 18:03
To be clear, I'm not necessarily against doing that.  EL5 is terribly old.  If we do decide that EL5-compatibility doesn't matter, we can also make the minimum version of bash 4.  That would allow some code cleanup, such as being able to replace instances of `foo 2>&1 | bar` with `foo |& bar`.

**Comment by kimvette** [comment] 2016-05-26 20:43
Considering that RHEL5 is past EOL and we're not selling it any more it's a nonissue, as customers will likely be more eager to migrate to RHEL7 as compliance security requirements (PCI, HIPAA regs, etc.) necessitate updates.

**Comment by carlwgeorge** [comment] 2016-05-26 20:56
EL5 doesn't go EOL until [2017-03-31](https://access.redhat.com/support/policy/updates/errata/#Life_Cycle_Dates).  Whether or not Rackspace sells EL5 anymore doesn't matter, because this is a public project.

**Comment by JayGoldberg** [comment] 2016-06-08 06:30
I like the idea of being more agnostic, perhaps using `/proc/<PID>/stat`?

**Comment by tonyskapunk** [comment] 2017-01-13 17:22
For this one the easiest is to wait until RHEL/CentOS 5 is EOL (two months from now) as I don't know how much of an effort will be to do the calculation using `/proc/PID/`. Is not the best option but we can put those efforts into something else as currently there is a good amount of PR that require attention so we can have a new release.

**Comment by carlwgeorge** [comment] 2017-01-13 17:41
You don't have to wait until EL5 EOL, just go ahead and include new minimum requirements in the release notes (i.e. bash >= 4, sysstat >= 9, etc).  That would be clear indication for packaging that the update won't be published for EL5.

**Comment by tonyskapunk** [comment] 2017-01-20 15:49
@carlwgeorge sounds good, since at this point we are aiming for v `1.0` I'm going to close #71 and reuse part of that commit to include one single commit with these additions and bumping it to `1.0`

**Comment by tonyskapunk** [comment] 2017-05-15 21:16
At this point EL5 is EOL, I'm closing this as we are ready to launch `1.0.0` PR #89

**Closed by tonyskapunk** 2017-05-15 21:16 UTC
